# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2025-05-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20180709_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/915a72972033451b85cf44f43515de5e'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/915a72972033451b85cf44f43515de5e', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='fc7e0ca14d9143da9e8469d5adbe1f64', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
