# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2025-05-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagess', '0003_auto_20180709_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysusermodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='SysUserModel/%Y/%m/6b9ea2edf87b47d181a3f70fbea2dfdf', verbose_name='系统用户头像'),
        ),
    ]
